listenAddr = ":8080"
dockerURL = "unix:///var/run/docker.sock"

[[extensions]]
    name = "haproxy"
    configPath = "/etc/haproxy/haproxy.cfg"
    pidPath = "/etc/haproxy.pid"
    templatePath = "/templates/haproxy.cfg.template"
    BackendOverrideAddress = ""
    maxConn = 1024
    port = 80
    adminUser = "admin"
    adminPass = "interlock"

