version: '3'
services:
  reverse-proxy:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker --docker.network=proxy --defaultEntryPoints='http,https' \
      --entryPoints='Name:http Address::80' \
      --entryPoints='Name:https Address::443 TLS'
    networks:
      - proxy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
    restart: always

  mailcatcher:
    image: mailhog/mailhog
    user: root
    networks:
      - smtp
      - proxy
    ports:
      - 8025
      - "0.0.0.0:1025:25"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
    labels:
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailcatcher.${DOMAIN}"
    restart: always

networks:
  proxy:
    external:
      name: proxy
  smtp:
    external:
      name: smtp
