version: '2'
services:
  interlock:
    image: vixns/interlock:haproxy_reload
    command: "-D run -c /bin/config.toml"
    restart: always
    ports:
        - 8080
    networks:
      - proxy
    volumes:
      - ./config.toml:/bin/config.toml
      - ./templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock

  #portainer:
  #  image: portainer/portainer
  #  restart: always
  #  ports:
  #    - 9000
  #  networks:
  #    - proxy
  #  volumes:
  #    - ./portainer:/data
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  labels:
  #    interlock.hostname: portainer
  #    interlock.port: "9000"
  #    interlock.network: proxy
  #    interlock.domain: "${DOMAIN}"

  mailcatcher:
    image: mailhog/mailhog
    user: root
    networks:
      - smtp
      - proxy
    ports:
      - 8025
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
    labels:
      interlock.hostname: mailcatcher
      interlock.port: "8025"
      interlock.network: proxy
      interlock.domain: ${DOMAIN}
    restart: always

  haproxy:
    image: haproxy:alpine
    restart: always
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    labels:
      interlock.ext.name: haproxy
    networks:
      - proxy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

networks:
  proxy:
    external:
      name: proxy
  smtp:
    external:
      name: smtp
