#!/bin/bash

CAHOME=./CA

if [ "$1" = "" ]
then

echo Creating the CA...

# Note, if $CAHOME exists, will over write...
mkdir -p $CAHOME


# Generate root CA key
openssl genrsa -out $CAHOME/rootCA.key 2048

# Create an X.509 cert from the CA key
openssl req -x509 -sha256 -nodes -days 1024 -newkey rsa:2048 -key $CAHOME/rootCA.key -out $CAHOME/rootCA.crt

openssl pkcs12 -export -in $CAHOME/rootCA.crt -inkey $CAHOME/rootCA.key -out $CAHOME/rootCA.p12


else

# Generate user key
openssl genrsa -out "haproxy/$1.key" 2048

# Create certificate request
openssl req -new -sha256 -key "haproxy/$1.key" -out "haproxy/$1.csr"

# Sign and generate the user certificate from the
openssl x509 -sha256 -req -in "haproxy/$1.csr" -CA $CAHOME/rootCA.crt -CAkey $CAHOME/rootCA.key -CAcreateserial -out "haproxy/$1.crt" -days 500

cat  "haproxy/$1.crt" "haproxy/$1.key" > "haproxy/default.pem"

fi
